# Generated by Django 3.2.9 on 2021-11-23 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimid', models.IntegerField()),
                ('front_width', models.IntegerField()),
                ('front_aspect_ratio', models.IntegerField()),
                ('front_wheel_size', models.IntegerField()),
                ('rear_width', models.IntegerField()),
                ('rear_aspect_ratio', models.IntegerField()),
                ('rear_wheel_size', models.IntegerField()),
            ],
            options={
                'db_table': 'tires',
            },
        ),
        migrations.CreateModel(
            name='User_Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tires.tire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_tires',
            },
        ),
    ]
